redis:
    image: redis
    container_name: redis
    ports:
        - 6379:6379
    volumes:
        - ./redis/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf
    restart: always

mysql:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
    restart: always

mongo:
   image: mongo
   container_name: mongo
   restart: always
   ports:
      - 27017:27017
   environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - mysql:db
    ports:
        - 8080:80
    environment:
        - PMA_HOST=db
        - PMA_PORT=3306
    restart: always
